### PR TITLE
Remove extraneous or deprecated files and functions from CubeND branch

### PR DESCRIPTION
**Pull request by DanRyanIrish**
Cleans out a lot of now unneeded code from sunpycube.  This has been done in several commits so that it is easier to roll back if required.

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
@abit2 Would you like to give this PR a quick skim through and see if there's anything obvious I've removed incorrectly?  I'm pretty confident it's OK.

**Comment by DanRyanIrish** [comment]
@abit2 I've manually tried all the tests and they all still pass expect ```test_NDCubeSequence.test_slice_first_index_sequence```.  But this is an ```AssertionError``` so I think that's an issue with the test rather than the deletions.

**Comment by abit2** [comment]
@DanRyanIrish 
```python
(irispy-dev) ankit@ankit:~/workspace/GSOC/cube$ py.test sunpycube/cube/tests/test_NDCubeSequence.py 
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/ankit/workspace/GSOC/cube, inifile: setup.cfg
plugins: mock-1.6.0, hypothesis-3.11.6
collected 18 items 

sunpycube/cube/tests/test_NDCubeSequence.py ..................

=============================== warnings summary ===============================
None
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 18 passed, 1 warnings in 12.16 seconds ====================
(irispy-dev) ankit@ankit:~/workspace/GSOC/cube$ 
```

**Comment by DanRyanIrish** [comment]
Must be something odd at my end then.

**Pull request merged**
